<a href="https://colab.research.google.com/github/tranquangvu2003/Lab_ML_2024/blob/main/Lab1_21139615_Tran_Quang_Vu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1.1

In [36]:
def task1():
  n = int(input("Nhập chiều dài danh sách: "))

  L = []
  i = 0
  while i < n:
      a = int(input("Nhập số: "))
      L.append(a)
      i += 1
  print("Danh sách bạn đã nhập:", L)

  print("Max L:", max(L))
  print("Min L:",min(L))

  tong = 0
  for num in L:
      tong += num
  print("Tổng phần tử trong L là:", tong)

  L.sort()
  print("Danh sách sau khi sắp xếp:", L)

  def sodva(L):
      duong= 0
      am = 0
      for so in L:
          if so > 0:
              duong += 1
          elif so < 0:
              am += 1
      return duong, am


  soduong, soam = sodva(L)
  print("Số dương:", soduong)
  print("Số âm:", soam)

  def S(n):
    if n == 0:
      return 1
    else:
      return n*S(n-1)
task1()
s= int (input("inter num s: "))
print("compute S: S= ",S(s))


Nhập chiều dài danh sách: 6
Nhập số: -4
Nhập số: 2
Nhập số: -4
Nhập số: 9
Nhập số: 8
Nhập số: 4
Danh sách bạn đã nhập: [-4, 2, -4, 9, 8, 4]
Max L: 9
Min L: -4
Tổng phần tử trong L là: 15
Danh sách sau khi sắp xếp: [-4, -4, 2, 4, 8, 9]
Số dương: 4
Số âm: 2
inter num s: 3
compute S: S=  6


Task 1.3

In [38]:
class Post:
  def __init__(self, content, subject, likes):
    self.__content = content
    self.__subject = subject
    self.__likes = likes

class Account:
  def __init__(self, name, email, country, friends, posts):
    self.__name = name
    self.__email = email
    self.__country = country
    self.__friends = friends
    self.__posts = posts

  def getName(self):
        return self.__name
  def getCountry(self):
        return self.__country
  def getPosts(self):
        return self.__posts
  def __str__(self):
        return f"Account: {self.__name}, Email: {self.__email}, Country: {self.__country}"
  def addPost(self, post):
    self.__posts.append(post)

  def getMaxLikePostByFriend(self):
    max_Likes =0
    max_Posts = None
    for friend in self.__friends:
      for post in friend.getPost():
        if post.getLikes() >max_Likes:
          max_Likes = post.getLikes()
          max_Posts = post

class AccountManager:
  def __init__(self, account):
    self.__account = account
  def groupAccountsByPostLike(self):
    result = {}
    for account in self.__account:
      if len(account.getPosts()) < 10:
        result[account] = False
      else:
        result[account] = True
    return result

  def filterAccounts(self, country):
    filtered_accounts = [account for account in self.__account if account.getCountry() == country]
    sorted_accounts = sorted(filtered_accounts, key=lambda account: (-len(account.getPosts()), account.getName()))
    return sorted_accounts


account1 = Account("Vu", "Vu123@gmail.com", "VietNam", [], [])
account2 = Account("Duy", "Duy123@gmail.com", "UK", [], [])

post1 = Post("Bai1!", "A", 100)
post2 = Post("Bai2!", "B", 150)


account1.addPost(post1)
account2.addPost(post2)

account_manager = AccountManager([account1, account2])

grouped_accounts = account_manager.groupAccountsByPostLike()

max_like_post = account1.getMaxLikePostByFriend()
print("Bai viet nhieu like:", max_like_post.getContent() if max_like_post else "Khong co")

print("Tai khoan nhom:")
for account, has_many_posts in grouped_accounts.items():
    print(f"Tai khoan: {account}, so bai viet: {has_many_posts}")

filtered_accounts = account_manager.filterAccounts("UK")
print("\nTai khoan bi loc:")
for account in filtered_accounts:
    print(account)


Bai viet nhieu like: Khong co
Tai khoan nhom:
Tai khoan: Account: Vu, Email: Vu123@gmail.com, Country: VietNam, so bai viet: False
Tai khoan: Account: Duy, Email: Duy123@gmail.com, Country: UK, so bai viet: False

Tai khoan bi loc:
Account: Duy, Email: Duy123@gmail.com, Country: UK


Task2

In [39]:
# Task 2.1
import numpy as np
arr = np.arange(10, 26)
reversed_arr = np.flip(arr)
print("Mang ban dau:", arr)
print("Mang dao nguoc:", reversed_arr)

Mang ban dau: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
Mang dao nguoc: [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [40]:
# Task 2.2
input_array_2_2 = np.array([1, 2, 3, 4])
repeated_2_times = np.tile(input_array_2_2, 2)
repeated_3_times = np.tile(input_array_2_2, 3)
print("Mang ban dau:", input_array_2_2)
print("Lap lai 2 lan:", repeated_2_times)
print("Lap lai 3 lan:", repeated_3_times)


Mang ban dau: [1 2 3 4]
Lap lai 2 lan: [1 2 3 4 1 2 3 4]
Lap lai 3 lan: [1 2 3 4 1 2 3 4 1 2 3 4]


In [41]:
# Task2.3
input_array_2_3 = np.array([[0.42, 0.48, 0.32],
                            [0.74, 0.58, 0.38],
                            [0.51, 0.34, 0.15]])
specified_value = 0.5
output_array_2_3 = np.where(input_array_2_3 < specified_value, specified_value, input_array_2_3)
print("Mang ban dau:")
print(input_array_2_3)
print("Thay cac phan tu lon:")
print(output_array_2_3)

Mang ban dau:
[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Thay cac phan tu lon:
[[0.5  0.5  0.5 ]
 [0.74 0.58 0.5 ]
 [0.51 0.5  0.5 ]]
